In [45]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.9.0+cpu


In [46]:
# scalar

scalar = torch.tensor(7)


In [47]:
scalar

tensor(7)

In [48]:
scalar.ndim

0

In [49]:
scalar.item()

7

In [50]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [51]:
vector.ndim

1

In [52]:
vector.shape

torch.Size([2])

In [53]:
Matrix = torch.tensor([[7, 8], [9, 10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [54]:
Matrix.ndim

2

In [55]:
Matrix.shape

torch.Size([2, 2])

In [56]:
Matrix[1]

tensor([ 9, 10])

#TENSOR

In [57]:
Tensor = torch.tensor([[[1,2,3],
                       [4,6,6],
                       [7,8,9]]])

Tensor

tensor([[[1, 2, 3],
         [4, 6, 6],
         [7, 8, 9]]])

In [58]:
Tensor.ndim

3

In [59]:
Tensor.shape

torch.Size([1, 3, 3])

In [60]:
Tensor[0]

tensor([[1, 2, 3],
        [4, 6, 6],
        [7, 8, 9]])

Matrix and Tensor must write in Upper Case

#Ramdom Tensor

In [61]:
random_tensor = torch.rand(3, 4)

In [62]:
random_tensor

tensor([[0.6981, 0.5700, 0.2945, 0.8890],
        [0.0075, 0.1433, 0.9945, 0.7205],
        [0.3298, 0.9327, 0.0749, 0.2616]])

In [63]:
random_tensor.ndim

2

In [64]:
random_image_size_tensor = torch.rand(size=(224,224,3)) # h,w,color
random_image_size_tensor.ndim

3

# Zero and Ones

In [68]:
zeros = torch.zeros(size=(3,4))

In [69]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [70]:
ones = torch.ones(size=(3,4))
print(ones)
zeros = torch.zeros(size=(3,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [71]:
ones.dtype

torch.float32

# creating a range of tensors and tensor-like

In [78]:
one_to_ten =torch.arange(start=1, end=1000, step=77)

In [79]:
# tensor like

ten_zeros = torch.zeros_like(one_to_ten)

In [80]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatypes

In [84]:
float_32_tenosr = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               requires_grad=False)
float_32_tenosr

tensor([3., 6., 9.])

In [86]:
float_16_tensor = float_32_tenosr.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [87]:
float_32_tenosr * float_16_tensor

tensor([ 9., 36., 81.])

In [90]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [91]:
float_32_tenosr * int_32_tensor

tensor([ 9., 36., 81.])

### Getting  information from Tensor

In [92]:
some_tensor = torch.rand(3,4)

In [93]:
some_tensor

tensor([[0.5866, 0.4584, 0.5008, 0.0899],
        [0.7354, 0.4231, 0.0819, 0.1002],
        [0.9095, 0.9673, 0.1920, 0.2822]])

In [94]:
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is stored on: {some_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is stored on: cpu


 Manipulating Tensors