In [139]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.9.0+cpu


In [140]:
# scalar

scalar = torch.tensor(7)


In [141]:
scalar

tensor(7)

In [142]:
scalar.ndim

0

In [143]:
scalar.item()

7

In [144]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [145]:
vector.ndim

1

In [146]:
vector.shape

torch.Size([2])

In [147]:
Matrix = torch.tensor([[7, 8], [9, 10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [148]:
Matrix.ndim

2

In [149]:
Matrix.shape

torch.Size([2, 2])

In [150]:
Matrix[1]

tensor([ 9, 10])

#TENSOR

In [151]:
Tensor = torch.tensor([[[1,2,3],
                       [4,6,6],
                       [7,8,9]]])

Tensor

tensor([[[1, 2, 3],
         [4, 6, 6],
         [7, 8, 9]]])

In [152]:
Tensor.ndim

3

In [153]:
Tensor.shape

torch.Size([1, 3, 3])

In [154]:
Tensor[0]

tensor([[1, 2, 3],
        [4, 6, 6],
        [7, 8, 9]])

Matrix and Tensor must write in Upper Case

#Ramdom Tensor

In [155]:
random_tensor = torch.rand(3, 4)

In [156]:
random_tensor

tensor([[0.8984, 0.2578, 0.5409, 0.3208],
        [0.1340, 0.9596, 0.6341, 0.2598],
        [0.2700, 0.3648, 0.7041, 0.5324]])

In [157]:
random_tensor.ndim

2

In [158]:
random_image_size_tensor = torch.rand(size=(224,224,3)) # h,w,color
random_image_size_tensor.ndim

3

# Zero and Ones

In [159]:
zeros = torch.zeros(size=(3,4))

In [160]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [161]:
ones = torch.ones(size=(3,4))
print(ones)
zeros = torch.zeros(size=(3,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [162]:
ones.dtype

torch.float32

# creating a range of tensors and tensor-like

In [163]:
one_to_ten =torch.arange(start=1, end=1000, step=77)

In [164]:
# tensor like

ten_zeros = torch.zeros_like(one_to_ten)

In [165]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatypes

In [166]:
float_32_tenosr = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               requires_grad=False)
float_32_tenosr

tensor([3., 6., 9.])

In [167]:
float_16_tensor = float_32_tenosr.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [168]:
float_32_tenosr * float_16_tensor

tensor([ 9., 36., 81.])

In [169]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [170]:
float_32_tenosr * int_32_tensor

tensor([ 9., 36., 81.])

### Getting  information from Tensor

In [171]:
some_tensor = torch.rand(3,4)

In [172]:
some_tensor

tensor([[0.7358, 0.8674, 0.0772, 0.5302],
        [0.6623, 0.8120, 0.6808, 0.1641],
        [0.4776, 0.0303, 0.6804, 0.1789]])

In [173]:
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is stored on: {some_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is stored on: cpu


 Manipulating Tensors

In [174]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [175]:

tensor

tensor([1, 2, 3])

In [176]:
tensor - 10

tensor([-9, -8, -7])

In [177]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [178]:
# matrix multiplication element wise and dot product

#element wise multiplication
print (tensor, "*",tensor )
print (f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [179]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [180]:
# Matrix multiplication by hand\
10*10 + 20*20 + 30*30


1400

In [181]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

CPU times: user 1.02 ms, sys: 0 ns, total: 1.02 ms
Wall time: 1.22 ms


In [182]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 285 µs, sys: 37 µs, total: 322 µs
Wall time: 252 µs


tensor(14)

In [183]:
# MATRIX MULTIPLICATION RULES
# 1.the inner dimensions must match
# 2. the result muatix has the shape of outer dimension

# One of the most common error in deep learning: shape errors

In [184]:
# Shapes for matrix multipliacation
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [185]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [186]:
tensor_B.T.shape

torch.Size([2, 3])

In [187]:
tensor_B.shape

torch.Size([3, 2])

Manipulating Tensor( Tensor Operation)

 . Addition
 . Subtraction
 . Multiplication ( element-wise)
 . Division
 . Matrix multiplication



In [188]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [189]:
tensor * 10

tensor([10, 20, 30])

In [190]:
tensor

tensor([1, 2, 3])

In [191]:
tensor - 10

tensor([-9, -8, -7])

In [192]:
# try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

 ## Tensor Aggregation
 ( min , max , sum , etc )

In [193]:
# create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [194]:
#min
torch.min(x)

tensor(0)

In [195]:
# max

torch.max(x)

tensor(90)

In [196]:
torch.mean(x.type(torch.float32))
x.type(torch.float32).mean()


tensor(45.)

Finding the positional min and max

In [197]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [198]:
x.argmin() # find the position of the tensor with mininum value

tensor(0)

In [199]:
#find the position in tensor that has the max value

x.argmax()

tensor(9)

Reshaping , stacking , squeezing and unsqueezing tensors


In [200]:
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [201]:
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

# change the view


In [202]:
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [203]:
# CHanging z changs x (view of tensor shares the memory as the original imput)

z[:,0] = 5

z , x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

### `clone()` - Creating a Copy

Unlike `view()`, the `clone()` method creates a *new* tensor with its own memory. This means changes to the cloned tensor will not affect the original tensor, and vice versa.

In [204]:
x_original = torch.tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
x_cloned = x_original.clone()

print(f"Original tensor (x_original): {x_original}")
print(f"Cloned tensor (x_cloned): {x_cloned}")

x_cloned[0] = 99

print(f"\nOriginal tensor after modifying clone: {x_original}")
print(f"Cloned tensor after modifying clone: {x_cloned}")

Original tensor (x_original): tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Cloned tensor (x_cloned): tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

Original tensor after modifying clone: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Cloned tensor after modifying clone: tensor([99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])


### `squeeze()` - Removing single dimensions

`squeeze()` removes all single dimensions (dimensions of size 1) from the tensor. It's useful for getting rid of unnecessary dimensions.

In [205]:
x_reshaped = torch.arange(1.,10.).reshape(1, 9)
print(f"Original tensor with extra dimension: {x_reshaped} (Shape: {x_reshaped.shape})")

x_squeezed = x_reshaped.squeeze()
print(f"Squeezed tensor: {x_squeezed} (Shape: {x_squeezed.shape})")

# Example with multiple dimensions
x_multi_dim = torch.rand(1, 10, 1, 5)
print(f"\nMulti-dimensional tensor: (Shape: {x_multi_dim.shape})")
x_multi_dim_squeezed = x_multi_dim.squeeze()
print(f"Squeezed multi-dimensional tensor: (Shape: {x_multi_dim_squeezed.shape})")

Original tensor with extra dimension: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) (Shape: torch.Size([1, 9]))
Squeezed tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) (Shape: torch.Size([9]))

Multi-dimensional tensor: (Shape: torch.Size([1, 10, 1, 5]))
Squeezed multi-dimensional tensor: (Shape: torch.Size([10, 5]))


### `unsqueeze()` - Adding a single dimension

`unsqueeze()` adds a single dimension of size 1 at a specified position (`dim`). This is often used to prepare tensors for operations that expect a certain number of dimensions (e.g., adding a batch dimension).

In [206]:
x_original = torch.arange(1.,10.)
print(f"Original tensor: {x_original} (Shape: {x_original.shape})")

x_unsqueeze_dim0 = x_original.unsqueeze(dim=0)
print(f"Unsqueezed at dim=0: {x_unsqueeze_dim0} (Shape: {x_unsqueeze_dim0.shape})")

x_unsqueeze_dim1 = x_original.unsqueeze(dim=1)
print(f"Unsqueezed at dim=1: {x_unsqueeze_dim1} (Shape: {x_unsqueeze_dim1.shape})")

Original tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) (Shape: torch.Size([9]))
Unsqueezed at dim=0: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) (Shape: torch.Size([1, 9]))
Unsqueezed at dim=1: tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]]) (Shape: torch.Size([9, 1]))


In [213]:
# torch.permute - rearranges the dimensions of a target tensor in a specificed order

x_original = torch.rand(size=(244,244,3))# h,2,colors

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0 ,1) #shifts axis 0->1 , 1->2. 2->0

print(f"previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

previous shape: torch.Size([244, 244, 3])
New shape: torch.Size([3, 244, 244])
