In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.9.0+cpu


In [3]:
# scalar

scalar = torch.tensor(7)


In [4]:
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
Matrix = torch.tensor([[7, 8], [9, 10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
Matrix.ndim

2

In [12]:
Matrix.shape

torch.Size([2, 2])

In [13]:
Matrix[1]

tensor([ 9, 10])

#TENSOR

In [14]:
Tensor = torch.tensor([[[1,2,3],
                       [4,6,6],
                       [7,8,9]]])

Tensor

tensor([[[1, 2, 3],
         [4, 6, 6],
         [7, 8, 9]]])

In [15]:
Tensor.ndim

3

In [16]:
Tensor.shape

torch.Size([1, 3, 3])

In [17]:
Tensor[0]

tensor([[1, 2, 3],
        [4, 6, 6],
        [7, 8, 9]])

Matrix and Tensor must write in Upper Case

#Ramdom Tensor

In [18]:
random_tensor = torch.rand(3, 4)

In [19]:
random_tensor

tensor([[0.0015, 0.0365, 0.6689, 0.3451],
        [0.0260, 0.3824, 0.1191, 0.5468],
        [0.1608, 0.3691, 0.8636, 0.8364]])

In [20]:
random_tensor.ndim

2

In [21]:
random_image_size_tensor = torch.rand(size=(224,224,3)) # h,w,color
random_image_size_tensor.ndim

3

# Zero and Ones

In [22]:
zeros = torch.zeros(size=(3,4))

In [23]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
ones = torch.ones(size=(3,4))
print(ones)
zeros = torch.zeros(size=(3,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [25]:
ones.dtype

torch.float32

# creating a range of tensors and tensor-like

In [26]:
one_to_ten =torch.arange(start=1, end=1000, step=77)

In [27]:
# tensor like

ten_zeros = torch.zeros_like(one_to_ten)

In [28]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatypes

In [29]:
float_32_tenosr = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               requires_grad=False)
float_32_tenosr

tensor([3., 6., 9.])

In [30]:
float_16_tensor = float_32_tenosr.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_32_tenosr * float_16_tensor

tensor([ 9., 36., 81.])

In [32]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [33]:
float_32_tenosr * int_32_tensor

tensor([ 9., 36., 81.])

### Getting  information from Tensor

In [34]:
some_tensor = torch.rand(3,4)

In [35]:
some_tensor

tensor([[0.0494, 0.1407, 0.8063, 0.8134],
        [0.6624, 0.2460, 0.4785, 0.5880],
        [0.5692, 0.1487, 0.5186, 0.7316]])

In [36]:
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is stored on: {some_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is stored on: cpu


 Manipulating Tensors

In [37]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [48]:

tensor

tensor([10, 20, 30])

In [40]:
tensor - 10

tensor([ 0, 10, 20])

In [41]:
torch.add(tensor,10)

tensor([20, 30, 40])

In [43]:
# matrix multiplication element wise and dot product

#element wise multiplication
print (tensor, "*",tensor )
print (f"Equals: {tensor * tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [47]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(1400)

In [49]:
# Matrix multiplication by hand\
10*10 + 20*20 + 30*30


1400

In [50]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

CPU times: user 1.88 ms, sys: 0 ns, total: 1.88 ms
Wall time: 3.11 ms


In [51]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 238 µs, sys: 22 µs, total: 260 µs
Wall time: 208 µs


tensor(1400)

In [ ]:
# MATRIX MULTIPLICATION RULES
# 1.the inner dimensions must match
# 2. the result muatix has the shape of outer dimension

# One of the most common error in deep learning: shape errors

In [62]:
# Shapes for matrix multipliacation
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [57]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [61]:
tensor_B.T.shape

torch.Size([2, 3])

In [60]:
tenosr_B.shape

torch.Size([3, 2])