In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.9.0+cpu


In [2]:
# scalar

scalar = torch.tensor(7)


In [3]:
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
Matrix = torch.tensor([[7, 8], [9, 10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
Matrix.ndim

2

In [11]:
Matrix.shape

torch.Size([2, 2])

In [12]:
Matrix[1]

tensor([ 9, 10])

#TENSOR

In [13]:
Tensor = torch.tensor([[[1,2,3],
                       [4,6,6],
                       [7,8,9]]])

Tensor

tensor([[[1, 2, 3],
         [4, 6, 6],
         [7, 8, 9]]])

In [14]:
Tensor.ndim

3

In [15]:
Tensor.shape

torch.Size([1, 3, 3])

In [16]:
Tensor[0]

tensor([[1, 2, 3],
        [4, 6, 6],
        [7, 8, 9]])

Matrix and Tensor must write in Upper Case

#Ramdom Tensor

In [17]:
random_tensor = torch.rand(3, 4)

In [18]:
random_tensor

tensor([[0.4548, 0.9790, 0.4781, 0.4015],
        [0.8737, 0.1676, 0.4774, 0.6531],
        [0.5366, 0.2214, 0.6574, 0.8665]])

In [19]:
random_tensor.ndim

2

In [20]:
random_image_size_tensor = torch.rand(size=(224,224,3)) # h,w,color
random_image_size_tensor.ndim

3

# Zero and Ones

In [21]:
zeros = torch.zeros(size=(3,4))

In [22]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
ones = torch.ones(size=(3,4))
print(ones)
zeros = torch.zeros(size=(3,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [24]:
ones.dtype

torch.float32

# creating a range of tensors and tensor-like

In [25]:
one_to_ten =torch.arange(start=1, end=1000, step=77)

In [26]:
# tensor like

ten_zeros = torch.zeros_like(one_to_ten)

In [27]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatypes

In [28]:
float_32_tenosr = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               requires_grad=False)
float_32_tenosr

tensor([3., 6., 9.])

In [29]:
float_16_tensor = float_32_tenosr.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_32_tenosr * float_16_tensor

tensor([ 9., 36., 81.])

In [31]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [32]:
float_32_tenosr * int_32_tensor

tensor([ 9., 36., 81.])

### Getting  information from Tensor

In [33]:
some_tensor = torch.rand(3,4)

In [34]:
some_tensor

tensor([[0.1272, 0.0579, 0.8236, 0.4140],
        [0.1199, 0.0313, 0.7898, 0.2678],
        [0.4705, 0.5107, 0.3114, 0.2589]])

In [35]:
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is stored on: {some_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is stored on: cpu


 Manipulating Tensors

In [36]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [37]:

tensor

tensor([1, 2, 3])

In [38]:
tensor - 10

tensor([-9, -8, -7])

In [39]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [40]:
# matrix multiplication element wise and dot product

#element wise multiplication
print (tensor, "*",tensor )
print (f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [41]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [42]:
# Matrix multiplication by hand\
10*10 + 20*20 + 30*30


1400

In [43]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

CPU times: user 545 µs, sys: 942 µs, total: 1.49 ms
Wall time: 1.66 ms


In [44]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 201 µs, sys: 469 µs, total: 670 µs
Wall time: 946 µs


tensor(14)

In [45]:
# MATRIX MULTIPLICATION RULES
# 1.the inner dimensions must match
# 2. the result muatix has the shape of outer dimension

# One of the most common error in deep learning: shape errors

In [50]:
# Shapes for matrix multipliacation
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [52]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [53]:
tensor_B.T.shape

torch.Size([2, 3])

In [55]:
tensor_B.shape

torch.Size([3, 2])

Manipulating Tensor( Tensor Operation)

 . Addition
 . Subtraction
 . Multiplication ( element-wise)
 . Division
 . Matrix multiplication



In [56]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [57]:
tensor * 10

tensor([10, 20, 30])

In [58]:
tensor

tensor([1, 2, 3])

In [59]:
tensor - 10

tensor([-9, -8, -7])

In [60]:
# try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

 ## Tensor Aggregation
 ( min , max , sum , etc )

In [63]:
# create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [64]:
#min
torch.min(x)

tensor(0)

In [66]:
# max

torch.max(x)

tensor(90)

In [73]:
torch.mean(x.type(torch.float32))
x.type(torch.float32).mean()


tensor(45.)

Finding the positional min and max

In [74]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [76]:
x.argmin() # find the position of the tensor with mininum value

tensor(0)

In [77]:
#find the position in tensor that has the max value

x.argmax()

tensor(9)